project:
  type: website
  output-dir: _site

website:
  title: "Armein Z. R. Langi"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "UTS"
        menu:
          - text: "UTS-1 All About Me"
            href: uts1.qmd
          - text: "UTS-2 My Songs for You"
            href: uts2.qmd
          - text: "UTS-3 My Stories for You"
            href: uts3.qmd
      - text: "UAS"
        menu:
          - text: "UAS-1 My Concepts"
            href: uas1.qmd
      - text: "Summary"
        href: summary.qmd
      - text: "References"
        href: references.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - uts1.qmd
      - uts2.qmd
      - uts3.qmd
      - uas1.qmd
      - summary.qmd
      - references.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    number-sections: true
    smooth-scroll: true
