project:
  type: book
  output-dir: docs

book:
  title: "Kyan Saktya Diraya"
  subtitle: "Portfolio Asesmen II-2100 KIPP"
  author: "Kyan Saktya Diraya"
  date: "9/15/2025"
  chapters:
    - index.qmd
    - All_About_me/index.qmd
    - My_Song_for_You/index.qmd
    - My_Stories_for_You/index.qmd
    - My_Shapes/index.qmd
    - My_Personal_Reviews/index.qmd
    - My_Concepts/index.qmd
    - My_Opinions/index.qmd
    - My_Innovations/index.qmd
    - My_Knowledge/index.qmd
    - My_Professional_Reviews/index.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - darkly
      - netflix-theme.scss
    backgroundcolor: "#141414"
    fontcolor: "#FFFFFF"
    linkcolor: "#E50914"
    toc: true
    toc-depth: 3
    smooth-scroll: true
  pdf:
    documentclass: scrreprt



